version: 0.2
phases:
  install:
    commands:
    # 필요한 패키지 설치 등
  pre_build:
    commands:
    # 빌드 준비 등
  build:
    commands:
      ./gradlew build  # 예시: Spring Boot 빌드
  post_build:
    commands:
      # 여기서 EC2로 배포(ssh/scp) 및 서버 재시작
      scp -i /path/to/key.pem build/libs/oneclass-0.0.1-SNAPSHOT.jar ec2-user@[EC2-IP]:~/oneclass-0.0.1-SNAPSHOT.jar
      ssh -i /path/to/key.pem ec2-user@[EC2-IP] "pkill -f 'java' || true"
      ssh -i /path/to/key.pem ec2-user@[EC2-IP] "nohup java -jar ~/oneclass-0.0.1-SNAPSHOT.jar > ~/app.log 2>&1 &"
artifacts:
  files:
    - build/libs/oneclass-0.0.1-SNAPSHOT.jar