version: 0.2

env:
  variables:
    EC2_HOST: "13.125.229.116"
    EC2_USER: "ubuntu"
    JAR_NAME: "oneclass-0.0.1-SNAPSHOT.jar"

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/key.pem
      - chmod 600 ~/.ssh/key.pem
      - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  pre_build:
    commands:
      - echo "빌드 시작"

  build:
    commands:
      - ./gradlew clean build -x test

  post_build:
    commands:
      - ls -al build/libs/
      - scp -i ~/.ssh/key.pem build/libs/$JAR_NAME $EC2_USER@$EC2_HOST:~/
      - ssh -i ~/.ssh/key.pem $EC2_USER@$EC2_HOST "ls -al ~/"
      # 자바 프로세스가 없으면 0 반환, 있어도 현재 bash는 안죽임
      - ssh -i ~/.ssh/key.pem $EC2_USER@$EC2_HOST "pgrep -fl java; pids=\$(pgrep -f $JAR_NAME); if [ -n \"\$pids\" ]; then kill \$pids; fi; sleep 2"
      # 또는 pkill의 결과를 무시해 확실히 종료코드 0으로 만듦
      # - ssh -i ~/.ssh/key.pem $EC2_USER@$EC2_HOST "pkill -f $JAR_NAME || true"
      - ssh -i ~/.ssh/key.pem $EC2_USER@$EC2_HOST "nohup java -jar ~/$JAR_NAME > ~/app.log 2>&1 &"
      - ssh -i ~/.ssh/key.pem $EC2_USER@$EC2_HOST "tail -n 10 ~/app.log"
      - echo "배포 완료"

artifacts:
  files:
    - build/libs/$JAR_NAME